import type { Metadata } from "next";
import { Inter, Pacifico, Bebas_Neue, Indie_Flower } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const pacifico = Pacifico({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-pacifico",
});
const bebas_neue = Bebas_Neue({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-bebasNeue",
});
const indie_flower = Indie_Flower({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-indieFlower",
});

export const metadata: Metadata = {
  title: "Daily Horoscope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pacifico.variable} ${bebas_neue.variable} ${indie_flower.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
